### ISSUE TITLE
Losing projects

### ISSUE THREAD

**Issue by mikecarr** [yuguang/fiddlesalad#33]
I created a fiddle, saved it, and lost everything. Dashboard shows nothing, is this no longer supported?

**Comment by yuguang** [comment]
Saving works. Try it again or watch this video
https://www.youtube.com/watch?v=MlMR0NxWt0o

Yuguang

**Comment by mikecarr** [comment]
I watched the video but I do not see where you saved the project.

Here is what I am seeing
https://www.youtube.com/watch?v=_FZvKWYlcCc&feature=youtu.be

**Comment by yuguang** [comment]
The problem is caused by something specific to your computer. You can see
recent fiddles have been saved: http://fiddlesalad.com/fiddles/. Maybe try
ctrl-f5 to reload the page without cache? Or check for network errors in
the console.

Yuguang

**Comment by Nayanne** [comment]
como faço para salvar meu projeto não estou conseguindo só da um erro dizendo que tem erros ortograficos.
